customhost = "database-1.cyq6ppvuh1ze.us-east-1.rds.amazonaws.com"
customuser = "aws_user"
custompass = "Bait3273"
customdb = "employee"
custombucket = "khoohongfung-employee"
customregion = "us-east-1"
